######################################################################
# WARNING: 'lib/Config_git.pl' is generated by make_patchnum.pl
#          DO NOT EDIT DIRECTLY - edit make_patchnum.pl instead
######################################################################
$Config::Git_Data=<<'ENDOFGIT';
git_commit_id='275243fbaf44bf18a6a42a38e62026bc22e22cc4'
git_describe='v5.41.8'
git_branch='v5.41.8'
git_uncommitted_changes=''
git_commit_id_title='Snapshot of:'
git_commit_date='2025-01-20 20:14:41 +0000'
git_snapshot_date='2025-01-20 20:14:41 +0000'

ENDOFGIT
